# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "28ac282496209c355e22f82feb72378c"
name = "ships"
handle = "ships"
application_url = "https://response-personnel-opponent-kansas.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "oroa-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://response-personnel-opponent-kansas.trycloudflare.com/auth/callback",
  "https://response-personnel-opponent-kansas.trycloudflare.com/auth/shopify/callback",
  "https://response-personnel-opponent-kansas.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
